export const dummy_communityList = [
  {
    id: 0,
    community_name: "전체",
    isClick: true,
  },
  {
    id: 1,
    community_name: "정보처리기능사",
    isClick: false,
  },
  {
    id: 2,
    community_name: "정보처리기사",
    isClick: false,
  },
  {
    id: 3,
    community_name: "정보처리산업기사",
    isClick: false,
  },
  {
    id: 4,
    community_name: "정보보안기사",
    isClick: false,
  },
];

export const dummy_communityDetail = [
  {
    id: 0,
    community_name: "정보처리기능사",
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    period: "2주",
    startDate: "2024-04-01",
    endDate: "2024-04-07",
    book: "x",
    result: "합격",
    study: "1주차에는 개념 정리 \n2주차에는 기출문제 풀기",
    heart: 122,
    heartClick: false,
    comment: 122,
    commentClick: false,
    bookmark: true,
  },
  {
    id: 1,
    community_name: "정보처리기사",
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김도영",
    date: "2023.02.04",
    period: "2주",
    startDate: "2024-04-01",
    endDate: "2024-04-08",
    book: "x",
    result: "합격",
    study: "1주차에는 개념 정리 \n2주차에는 기출문제 풀기",
    heart: 123,
    heartClick: true,
    comment: 123,
    commentClick: true,
    bookmark: true,
  },
  {
    id: 2,
    community_name: "정보처리산업기사",
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김도영",
    date: "2023.02.04",
    period: "2주",
    startDate: "2024-04-01",
    endDate: "2024-04-02",
    book: "x",
    result: "합격",
    study: "1주차에는 개념 정리 \n2주차에는 기출문제 풀기",
    heart: 123,
    heartClick: true,
    comment: 123,
    commentClick: true,
    bookmark: true,
  },
  {
    id: 3,
    community_name: "정보보안기사",
    profileImg: require("assets/icons/archives/profile.png"),
    name: "이제호",
    date: "2023.02.04",
    period: "2주",
    startDate: "2024-04-01",
    endDate: "2024-04-20",
    book: "x",
    result: "합격",
    study: "1주차에는 개념 정리 \n2주차에는 기출문제 풀기",
    heart: 123,
    heartClick: true,
    comment: 123,
    commentClick: true,
    bookmark: true,
  },
  {
    id: 4,
    community_name: "정보보안기사",
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김도영",
    date: "2023.02.04",
    period: "2주",
    startDate: "2024-04-01",
    endDate: "2024-04-17",
    book: "x",
    result: "합격",
    study: "1주차에는 개념 정리 \n2주차에는 기출문제 풀기",
    heart: 123,
    heartClick: true,
    comment: 123,
    commentClick: true,
    bookmark: true,
  },
];

export const dummy_comment = [
  {
    id: 0,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김도영",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
  {
    id: 1,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
  {
    id: 2,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
  {
    id: 3,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
  {
    id: 4,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
  {
    id: 5,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
  {
    id: 6,
    profileImg: require("assets/icons/archives/profile.png"),
    name: "김똥",
    date: "2023.02.04",
    comment: "이 자료 덕분에 합격했어요! 감사합니다 :)",
  },
];